// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANRNZ-VGRVGGqJz33HblszRJPJ-O329tw',
    appId: '1:287124774678:web:a8c07bb47f2666fb44ba37',
    messagingSenderId: '287124774678',
    projectId: 'hemingway-705f5',
    authDomain: 'hemingway-705f5.firebaseapp.com',
    storageBucket: 'hemingway-705f5.appspot.com',
    measurementId: 'G-Y1ZDE4RXY0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE4FVEEwOlKA_c9ExBmrshHnD_h9OPog0',
    appId: '1:287124774678:android:a4f8e1102fd1866444ba37',
    messagingSenderId: '287124774678',
    projectId: 'hemingway-705f5',
    storageBucket: 'hemingway-705f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe0iW9k-DLafp7dAo0BwYn1F0lTz05fZg',
    appId: '1:287124774678:ios:e7b2aa9a2a49ab6e44ba37',
    messagingSenderId: '287124774678',
    projectId: 'hemingway-705f5',
    storageBucket: 'hemingway-705f5.appspot.com',
    iosClientId: '287124774678-ae3ur5l1ophjqp9m4d2qskohdhvmlp5r.apps.googleusercontent.com',
    iosBundleId: 'com.example.hemingway',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe0iW9k-DLafp7dAo0BwYn1F0lTz05fZg',
    appId: '1:287124774678:ios:e7b2aa9a2a49ab6e44ba37',
    messagingSenderId: '287124774678',
    projectId: 'hemingway-705f5',
    storageBucket: 'hemingway-705f5.appspot.com',
    iosClientId: '287124774678-ae3ur5l1ophjqp9m4d2qskohdhvmlp5r.apps.googleusercontent.com',
    iosBundleId: 'com.example.hemingway',
  );
}
